name: add version tag
on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed

  push:
    branches:
      - feature/add-release-flow

jobs:
  release:
    name: add tag
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}
      - run: git checkout ${{ github.event.pull_request.head.ref }}
      - run: git tag `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'`
      - run: git push origin `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'`
